### ISSUE TITLE
Let parametrize IComparer via constructors

### ISSUE THREAD

**Issue by mat-pielat** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#26]
A simple addition which lets people prioritize maximum elements over minimum ones. It also nicely decouples the default comparer of the priority class from the one used in the queue.

**Comment by BlueRaja** [comment]
I tested this before and it resulted in performance degradation _(yes, I expected the JIT to optimize it away also, but apparently it does not do so completely)_.

There'd be no way to do this in only `SimplePriorityQueue` without rewriting a large portion of it _(since it relies on `FastPriorityQueue`)_, so I have to deny this request, sorry.

**Comment by BlueRaja** [comment]
Ah, sorry I was misremembering!  I do use `IComparer` for `SimplePriorityQueue`, so this would be possible.  Hmm.

**Comment by BlueRaja** [comment]
Completed in v4.1.1
`SimplePriorityQueue` can now take a `IComparer<TPriority>` or `Comparison<TPriority>` in its constructor.
