### ISSUE TITLE
Add constructor accepting FastPriorityQueue's backing array to minimize allocation

### ISSUE THREAD

**Issue by mchandschuh** [BlueRaja/High-Speed-Priority-Queue-for-C-Sharp#50]
For my use case, I'll have an unknown number of queues processing at the same time and in quick succession. It would be ideal if I could use `ArrayPool` to pool array allocations and then initialize `FastPriorityQueue` using the pool sourced array.

**Comment by BlueRaja** [comment]
I'm not sure if there's a way to make this faster than just calling `.Clear()`. The heap relies on the array being zero-initialized - if the backing array is reused between instances without being cleared, it's possible for `Contains()` to give a false-positive.

[Edit] Going to close this because of the above issue. If you disagree, please reopen.
